### ISSUE TITLE
Update pcf command for 1.8 API changes

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#112]
1.8 includes a massive API update, and while most of the pcf commands continue to work using the old APIs, it would greatly benefit from using the new ones (while somehow maintaining compatibility with older versions, of course)

**Comment by mboldt** [comment]
Brief update: I added `opsmgr.get_version()` that returns the Ops Manager version (e.g., version 1.8.0 would return `[1, 8, 0]`). Sample use in `opsmgr.configure()`.
