### ISSUE TITLE
Tile-generator should start using real releases

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#123]
And releases should only be tagged/published when the pipeline delivers them

**Comment by mboldt** [comment]
Real releases are now posted to [PyPI](https://pypi.python.org/pypi/tile-generator/) from the CI pipeline, and can be installed via `pip install tile-generator`. Dev releases are tagged and uploaded to [GitHub releases](https://github.com/cf-platform-eng/tile-generator/releases) from the CI pipeline, and can be installed with `pip install tile-generator-<version>.tar.gz`. Dev releases are created for every commit to master. Real releases are manually triggered by CI jobs for major, minor, and patch version.
