### ISSUE TITLE
How to pass password in form properties?

### ISSUE THREAD

**Issue by kartiklunkad26** [cf-platform-eng/tile-generator#129]
Hi! 
I was wondering if we could update the documentation to represent passwords while creating properties in forms on the tile?

**Comment by guidowb** [comment]
Added a field of type `secret` to `sample/tile.yml` and 'sample/missing-properties.yml`. Added documentation for both to the documentation pages for tile-generator and the`pcf`command. Clarified that the value of a`secret` field will be passed as plain text in an environment variable to all applications.
