### ISSUE TITLE
Deliver tile-generator in a docker image

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#139]
This would be the image created in install-tile-generator
It should be delivered to cfplatformeng rather than guidowb on DockerHub
We should link to it from the documentation pages, and describe supported use

**Comment by guidowb** [comment]
Should also relocate the base pipeline image, but not make it public

**Comment by JaredGordon** [comment]
see here: 
https://github.com/cf-platform-eng/tile-inator
https://hub.docker.com/r/cfplatformeng/tile-inator

is this what you are looking for?

**Comment by mboldt** [comment]
We have a nearly-identical Dockerfile in our CI pipeline:
https://github.com/cf-platform-eng/tile-generator/blob/master/ci/docker-tile-generator/Dockerfile
It would be nice to use this one since it gets tested, but we'll have to make sure we only publish official releases and not dev builds.

**Comment by guidowb** [comment]
Official releases of tile-generator as now available on Dockerhub at cfplatformeng/tile-generator. That image contains the `tile` and `pcf` commands, as well as all Python dependencies and the BOSH CLI. The `latest` tag will always refer to the most recent official release (no pre-releases).
