### ISSUE TITLE
Better validation in "pcf configure"

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#147]
In 1.8, you can have optional properties with no values. See #146 for a PR that basically tells the `configure` command to skip validation entirely.

It would be better, though, to only validation the things that need validation. `/api/installation_settings`, though, doesn't include what you need to differentiate optional from non-optional. Is there some other way?

**Comment by cholick** [comment]
@mboldt

**Comment by keshto** [comment]
merged
