### ISSUE TITLE
1 is not vaild value for ignore_warnings=1

### ISSUE THREAD

**Issue by Infra-Red** [cf-platform-eng/tile-generator#175]
PCF Ops Manager v1.8.16.0
https://opsman-dev-api-docs.cfapps.io/#triggering-an-install-process
```
⟫ pcf apply-changes
- 422 https://opsmanager.example.com/api/installation?ignore_warnings=1
- [
-     "'1' is not a valid value for 'ignore_warnings=1'"
- ]
```
Everything works fine if i provide `true` instead of `1` to `ignore_warnings`

```
curl -vv -H 'Authorization: bearer ...' -k -X POST https://opsmanager.example.com/api/installation?ignore_warnings=true

{"install":{"id":2}}
```

**Comment by guidowb** [comment]
Curious. This has worked against Ops Man versions from 1.5 to 1.10 for the past year or so, and we've never seen that error. Is it a 1.8.16 specific failure? Did something else change?

Before we merge this, I want to make sure the new value works with all our other versions. Need to figure out a way to test that.

**Comment by Infra-Red** [comment]
I can confirm that I get the same behaviour with PCF Ops Manager v1.9.7.0. Both are latest available build for 1.8 and 1.9.

**Comment by Infra-Red** [comment]
[OM](https://github.com/pivotal-cf/om) tool also sets `ignore_warnings` value to true or false.
https://github.com/pivotal-cf/om/blob/master/api/installations_service.go#L68-L71

**Comment by guidowb** [comment]
Right. But om uses the v0 api which is not available in the older versions we support. My concern is that some of those versions will not accept `true`, so we may need conditional code to pass in different values based on the version (or the specific 422)
