### ISSUE TITLE
Add more validation

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#187]
Three things that snuck through `tile build` that could be easily validated to avoid having to upload to ops manager for validation:
- missing `release` in job template
- validating property type (e.g., detect typos in a `type` field).
- having > 0 for either static_ip or dynamic_ip

**Comment by mboldt** [comment]
I don't want to re-implement ops manager, but I think validating simple things like this is relatively low cost for the high value of providing tile authors with fast feedback for a tighter iteration loop, rather than letting `tile build` succeed, uploading a tile to ops manager, and then getting relatively cryptic error messages about these issues.

**Comment by keshto** [comment]
Most of these are solved with new schema. Please open new issues for any missed ones
