### ISSUE TITLE
sample/resources directory missing redis-12+dev.1.tgz file for tg-test-app5

### ISSUE THREAD

**Issue by dbblackdiamond** [cf-platform-eng/tile-generator#192]
Hi,

I am new to PCF and have been trying to start experimenting with tiles. I cloned the tile-generator repo and followed the document at https://docs.pivotal.io/tiledev/tile-generator.html . When I ran the `tile build` command, everything went well, until it tried to build tg-test-app5 as it is looking for file redis-12+dev.1.tgz in the sample/resources directory and the file doesn't exist. 

Shouldn't the file be included in the repository so that the build can actually work? Alternatively, the tutorial should specify where to download the file from. 

Thanks a lot,
Bertrand.

**Comment by mboldt** [comment]
The file is relatively large for the repo, but I completely agree we should have a link to download in the documentation.

**Comment by mboldt** [comment]
In the meantime, just to avoid this issue, you can remove that package from the sample tile's tile.yml (i.e., remove these lines: https://github.com/cf-platform-eng/tile-generator/blob/master/sample/tile.yml#L316-L381).

**Comment by gberche-orange** [comment]
@mboldt I'm also having issues with the  tg_test_app3 when using the tile generator docker image:

```
$ cd tile-generator/sample

$ docker pull guidowb/sample-cf-app
[...]
$ docker images | grep sample-cf-app
guidowb/sample-cf-app          latest              08e2c98605dd        9 months ago        62.9 MB

$ docker run -it -v `pwd`:`pwd` -w `pwd` cfplatformeng/tile-generator 
$ ./src/build.sh
$ tile build
[...]
bosh add-blob /home/guillaume/public-code/cf/tile-generator/sample/release/test-tile/blobs/tg_test_app3/manifest.yml tg_test_app3/manifest.yml
bosh generate-package tg_test_app4
guidowb/sample-cf-app not found on local machine
you must either pull the image, or download it and use the --cache option
```

**Comment by gberche-orange** [comment]
Edit: after modifying `/usr/lib/python2.7/site-packages/tile_generator/util.py` to print the exception and traceback, I'm getting

```
# tile build
...
bosh add-blob /home/guillaume/public-code/cf/tile-generator/sample/release/test-tile/blobs/tg_test_app3/manifest.yml tg_test_app3/manifest.yml
bosh generate-package tg_test_app4
guidowb/sample-cf-app not found on local machine (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', error(2, 'No such file or directory')),), <traceback object at 0x7f39e3ad2170>)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tile_generator/util.py", line 95, in download
    image = docker_cli.get_image(docker_image)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 18, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
you must either pull the image, or download it and use the --cache option
```

I guess there additional environment variables that need to be set when running `tile build` within the tile generator docker image. I'll try to get inspiration from https://github.com/cf-platform-eng/tile-generator/blob/2f426b28611717e41ac4fc7c07b75cf54661e939/ci/pipeline.yml#L437-L437

**Comment by mboldt** [comment]
I've made the required redis bosh release available here: https://drive.google.com/uc?export=download&id=0B4WUQaDAVbdzd3UwY3JlRW9tQVU

I will update the docs to link to it.

**Comment by mboldt** [comment]
Docs PR submitted (https://github.com/pivotal-cf/docs-book-tiledev/pull/32). @gberche-orange if you need further assistance, please open a separate issue.

**Comment by gberche-orange** [comment]
thanks @mboldt for publishing the redis release bits.
