### ISSUE TITLE
Constraints for cpu and memory

### ISSUE THREAD

**Issue by antonsoroko** [cf-platform-eng/tile-generator#197]
Hi!

Is there a reason why tile-generator do not create constraints for cpu/mem?
https://github.com/cf-platform-eng/tile-generator/blob/bccaf3128310ececafbe356d55f4b8b20ed27f84/tile_generator/templates/tile/metadata.yml#L451

It seems that it is easy to fix so I wondering maybe this was not done by some reason.

Thanks.

**Comment by guidowb** [comment]
Hi @antonsoroko,

You're right - we should probably be consistent and not allow users to dial those settings down below what the tile builder specified, just like we do for persistent disk.

Thanks for reporting it!

**Comment by mboldt** [comment]
Fix is working its way through CI before release. Should be in tile-generator 9.0.3.
