### ISSUE TITLE
Add support for custom service instance name in `auto_services`

### ISSUE THREAD

**Issue by royclarkson** [cf-platform-eng/tile-generator#198]
Currently, tile generator provisions services from `auto_services` using a predefined schema of `${PKG_NAME}-${SVC_NAME}` as seen [here](https://github.com/cf-platform-eng/tile-generator/blob/master/tile_generator/templates/jobs/deploy-all.sh.erb#L244). Please add support for another field, e.g. `service_instance` or something similar to `auto_services` so that the name of the provisioned service can be customized. Thanks.

**Comment by guidowb** [comment]
Fix will be included in tile-generator 9.0.1

**Comment by royclarkson** [comment]
@guidowb thanks for the quick response!

**Comment by guidowb** [comment]
@royclarkson Change made it through CI and was posted on Pypi. Please give it a try and let me know if it does what you expect. Thanks!
