### ISSUE TITLE
Migration rendering loses indentation (cosmetic)

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#201]
This tile.yml:
```
migration: |
  properties['properties']['.properties.org']['value'] = 'system';
  if (somekey in properties['properties']) {
    //set stuff
  }
```

Produces this migration:
```
exports.migrate = function(properties) {
    properties['properties']['.properties.org']['value'] = 'system';
if (somekey in properties['properties']) {
  //set stuff
}
    return properties;
};
```

which is really ugly because it loses the indents,
but JS doesn’t really care so I think it’s still valid

**Comment by mboldt** [comment]
I think we have an existing template filter to do the indentation, something like `{{ migration | indent }}` might fix it up.

**Comment by guidowb** [comment]
Combined with using a `|-` instead of just `|` in tile.yml, so that the whitespace gets preserved in the input, also
