### ISSUE TITLE
`pcf reboot` hangs on OM 1.11

### ISSUE THREAD

**Issue by mheath** [cf-platform-eng/tile-generator#203]
Running `pcf reboot` just hangs when running it against one of our OM 1.11 environments.

For Pivots, this can be reproduced using the `cyan` RGB environment. Ping me on Slack if you need credentials.

**Comment by mheath** [comment]
On PCF 1.10 the `ubuntu` user does not require a password to sudo (configured in `/etc/sudoers.d/90-ubuntu`). On PCF 1.11, `ubuntu` user is explicitly configured to prompt for a password (see `/etc/sudoers.d/90-ubuntu-with-password`).

`sudo` prompting for a password is what causes`pcf reboot` to hang.

**Comment by mheath** [comment]
Here's the really dumb thing though. The config `90-cloud-init-users` configures the `ubuntu` user to not require a password but then that gets overwritten by the `90-ubuntu-with-password` config. If you manually delete the no password config file, `pcf reboot` starts to work again.

**Comment by joeeltgroth** [comment]
Does the PCF environment have the the ubuntu user's password somewhere such that the code implementing 'pcf reboot' could fetch it and pass it through if needed?

**Comment by joeeltgroth** [comment]
Fixed as of this commit: https://github.com/cf-platform-eng/tile-generator/commit/4269c97b681748e96436d81e6db33cc58e917fc9
