### ISSUE TITLE
requires_product_versions: "'name': 'cf', 'version': '>= 1.9'" always appended even if config specifies another cf version

### ISSUE THREAD

**Issue by mikelangdon** [cf-platform-eng/tile-generator#218]
https://github.com/cf-platform-eng/tile-generator/blob/309784782de680f0249b2c041a698cf6ed479673/tile_generator/package_flags.py#L108

It's apparently not possible to specify a different minimum version of "cf" with the generator as written. If you do, both entries are in the resulting yaml (1.9 and whatever was specified in config). Behavior on install will vary between different install target versions.

`{'name': 'cf', 'version': '>= 1.9'}` should not be appended if the incoming config already has an entry with name "cf".

**Comment by pavankrish123** [comment]
We have hit this issue recently, especially because our tile is heavily dependent on cf > = 2.0.7 (reverse_log_proxy) BOSH links. Please fix this issue as soon as possible

**Comment by keshto** [comment]
Should be fixed in latest dev release. Will cut a new release once it passes all tests.
