### ISSUE TITLE
tile build fails on regex for job name with Capital letter or underscores

### ISSUE THREAD

**Issue by PhilippeKhalife** [cf-platform-eng/tile-generator#221]
Using latest checkout from tile-generator on master, an existing project that built on the last release 10.0.3 is failing:

mybosh-release -> Failed to validate: {'jobs': [{0: [{'name': ["value does not match regex '^[a-z][a-zA-Z0-9\\-]*$'"]}], 1: [{'name': ["value does not match regex '^[a-z][a-zA-Z0-9\\-]*$'"]}], 2: [{'name': ["value does not match regex '^[a-z][a-zA-Z0-9\\-]*$'"]}], 3: [{'name': ["value does not match regex '^[a-z][a-zA-Z0-9\\-]*$'"]}], 4: [{'name': ["value does not match regex '^[a-z][a-zA-Z0-9\\-]*$'"]}]}]}

Seems it does not like Capital letters for a job name..

**Comment by mboldt** [comment]
Another user reported the same issue with underscores, which should be allowed.

**Comment by keshto** [comment]
Fixed in https://github.com/cf-platform-eng/tile-generator/pull/222
