### ISSUE TITLE
Remove generated _HOST and _HOSTS for static jobs when bosh links are detected.

### ISSUE THREAD

**Issue by PhilippeKhalife** [cf-platform-eng/tile-generator#224]
There is a bug when using the generated _HOST and _HOSTS for jobs with static ips, as these entries are available for ALL Jobs.

So every job has properties _HOST and _HOSTS about every other job, this means that when an operator changes the number of instance for one job it will affect the other jobs during a deployment.

While I think this can be fixed on its own, I think a better solution is to use BOSH links.

I propose that when bosh links are detected that the tile generator stops producing the _HOST and _HOSTS properties.

**Comment by mboldt** [comment]
Is this still relevant with the recent move from `.ips`/`.first_ip` to BOSH links?

**Comment by PhilippeKhalife** [comment]
I think it is safe to say this can be closed - I checked with the latest build and the metadata file 👍
