### ISSUE TITLE
config_unittest.TestUltimateForm

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#227]
The file `tile_generator/test_config_expected_output` is a single line 73,752 characters long. Changing code that affects the final metadata results in some delta in this file, but not possible to actually test-drive any delta here: the expected output is unreadable. The file needs to be human readable.

**Comment by cholick** [comment]
https://github.com/cf-platform-eng/tile-generator/blob/master/tile_generator/config_unittest.py#L74

**Comment by keshto** [comment]
https://github.com/cf-platform-eng/tile-generator/commit/7886b59f052d88084793bc8e2cb488b27cb35134 this should make things better
