### ISSUE TITLE
run_local_tests.sh assumes tile on path reflects source code

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#229]
There are several ways to setup a local development environment. `run_local_tests.sh` assumes that invoking the `tile` command uses the current source. This is not true on my machine. There are safer ways to invoke the code such that it _ensures_ using the current source, for example (from the sample dir):

```
PYTHONPATH=`cd .. && pwd` python -m tile_generator.tile build
```

**Comment by keshto** [comment]
Won't fix. The script is meant for a dev environment only and in a dev environment in python `pip install -e .` is the way to work on a project.
