### ISSUE TITLE
Cannot produce a PCF 2.0 compliant tile while static_ip: 1

### ISSUE THREAD

**Issue by PhilippeKhalife** [cf-platform-eng/tile-generator#244]
When a job has static_ip: 1 ( Deprecated/ignored in PCF 2.1 but continues the same static assignment  ), the tile-generator produces static accessor  *_ips, *_ip

An accessor free PCF 2.0 compatible tile cannot be produced while static_ip: 1

To generate a static accessor free tile, setting the static_ip:0 and replacing with dynamic_ip: 1 produces a tile that fails testing on PCF 2.0.

Based on additional research with the Pivotal team we confirmed that PCF release 2.1 will deprecate and ignore static_ip while keeping the static behavior , so it is OK to keep static_ip: 1 in a tile and leave it.. making it work on current PCF releases.

The tile-generator needs a mechanism to switch off generating static accessors that is not linked to static_ip: 1

I think the options are either a new major release of the tile generator that drops the accessors given they are dropped from PCF 2.0 and PCF 2.1 , or a parameter to control them at build time.

**Comment by mboldt** [comment]
The fix is in. I will coordinate with @keshto and we should be able to cut a release this week.

**Comment by mboldt** [comment]
As of tile-generator 12.0.0, `static_ip: 1` no longer produces the `.ips` and `.first_ip` accessors. As you know, you can use BOSH links to obtain this host information for BOSH jobs.

For completeness, there is one more case where tile-generator uses `.ips` and `.first_ip`, which is when the tile includes a package of type `docker-bosh`. This will be removed in 12.0.1, and tile authors can use the BOSH link `docker-tcp` from the docker job to obtain the host information.
