### ISSUE TITLE
doc needed for sample tile

### ISSUE THREAD

**Issue by mnp** [cf-platform-eng/tile-generator#25]
The top level README.md does not indicate how to build the included sample tile.  Perhaps a section should be added there?  I am guessing the steps would be:
1. cd sample
2. ./src/build.sh
3. tile build

**Comment by guidowb** [comment]
Yes, those steps are correct. And I'll happily include them in the README. Thanks for the comment!

(If the sample is modified, additional steps are needed to include the sample app in the docker image for app3. That is currently only done by the CI pipeline using a Concourse docker resource)

**Comment by mnp** [comment]
Cool, thanks.
