### ISSUE TITLE
Unable to create a tile that contains external-broker package

### ISSUE THREAD

**Issue by k-kos** [cf-platform-eng/tile-generator#256]
I'm getting the following error message while trying to generate a tile that contains a package of `external-broker` type:
```
File "/usr/lib/python2.7/site-packages/tile_generator/tile_metadata.py", line 168, in _build_property_blueprints
  "configurable": True
TypeError: append() takes exactly one argument (3 given)
```

I assume that the issue is in this place:
https://github.com/cf-platform-eng/tile-generator/blob/5e7da5ffc0066b89c2be15199d44c6a0d35ea8fc/tile_generator/tile_metadata.py#L154
There is an attempt to add 3 elements by `append()` method.

**Comment by keshto** [comment]
https://github.com/cf-platform-eng/tile-generator/commit/a51dff72c5af115b5710bf61bca7828ead242160 should address the issue thanks
