### ISSUE TITLE
Omitting global defaults will cause a silent Ops Manager failure

### ISSUE THREAD

**Issue by mnp** [cf-platform-eng/tile-generator#26]
The tile.yml from both the sample and the `tile init` command have a global defaults section which, for my PCF (v1.6.9.0) at least, are not optional as indicated.  

``` sh
# Global defaults (all optional)
#
# org: test-org                         # Name of org to create for your apps
# org_quota: 4096                       # Memory quota for that org in MB
# space: test-space                     # Name of space to create for your apps
apply_open_security_group: true         # Apply open security group, default: false
```

Recipe:
- leave these commented out as above
- `tile build`
- import the .pivotal to Ops Manager
- `Add>>` the product
- Click the new (orange) tile
- Fill in required settings as indicated by orange circles and save
- Observe the tile has turned green

At this point, the "Apply Changes" button remains disabled with tool tip: "You must configure one or more PCF products before installing" and cannot be pressed.  There is no indication by orange circles etc what else needs to be configured.

Expected:

The YML should either be rejected at some point in the process with a useful message, or it should apply.

Workaround:

Uncommenting the global defaults and repeating the above will allow an apply.

I can attach an offending .pivotal if that would be helpful.

**Comment by guidowb** [comment]
I've reproduced this. Will work on a fix. Thanks for reporting it!
