### ISSUE TITLE
kibosh example chart should have something meaningful in plans/default.yaml

### ISSUE THREAD

**Issue by z4ce** [cf-platform-eng/tile-generator#264]
Right now it is empty and its unclear what if anything can be put into the plan yaml. The documentation should also talk about how to use plans.yaml.

**Comment by cholick** [comment]
Thanks Ian, we've put this near the top of the backlog.

**Comment by mboldt** [comment]
We've added a new example here: https://github.com/cf-platform-eng/tile-generator/tree/master/examples/kibosh-mysql/mysql with a simple example of multiple plans, with different configuration.

I'll add a story for improving the `plans.yaml` and `plans/*.yaml` documentation, but the quick answer is each `plans/*.yaml` file contains plan-specific overrides for your values.yaml file. There is a brief blurb in the [kibosh readme](https://github.com/cf-platform-eng/kibosh#changes-required-in-chart), but I agree it should be improved.

**Comment by cholick** [comment]
See
* https://github.com/pivotal-cf/docs-tiledev/pull/24
* https://github.com/cf-platform-eng/kibosh/blob/master/README.md#changes-required-in-chart
