### ISSUE TITLE
`consumes` block gets double-quoted

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#265]
E.g., in https://github.com/cf-platform-eng/pcf-examples/tree/master/tile-for-bosh-simple-with-routing

The tile metadata output by tile-generator includes:
```
  - consumes: |
      "nats:\n  from: nats\n  deployment: (( ..cf.deployment_name ))\n"
```
So the string is double-quoted (once by the `|`, once by the `"`s). This causes the failure:
```
Task 8620

Task 8620 | 10:14:55 | Preparing deployment: Preparing deployment (00:00:00)
                    L Error: Property 'consumes' value ("nats:\n  from: nats\n  deployment: cf-a110d623c47d71df85f5\n") did not match the required type 'Hash'
Task 8620 | 10:14:55 | Error: Property 'consumes' value ("nats:\n  from: nats\n  deployment: cf-a110d623c47d71df85f5\n") did not match the required type 'Hash'
```

Originally raised by a partner developing a tile, reproduced with our example above.

**Comment by keshto** [comment]
https://github.com/cf-platform-eng/tile-generator/tree/1965af088b96ae035ea41a29924102ef85acd27e should fix this
