### ISSUE TITLE
Tile Name with space doesn't work

### ISSUE THREAD

**Issue by rjain-pivotal** [cf-platform-eng/tile-generator#28]
If the tile name has spaces in the tile.yml, it breaks. Maybe you want to replace the name with underscore or dash in the bosh build

**Comment by guidowb** [comment]
Thanks Rajesh! Yeah, this is the Ops Manager product name. I'm a little worried about automatically correcting it, as it is used in so many places and I prefer that the user know exactly what it is. How about documenting the constraints, validating it, and giving a friendly message if it doesn't meet the constraints? Does that make sense to you?
