### ISSUE TITLE
tile.yml validation/schema

### ISSUE THREAD

**Issue by josephlewis42** [cf-platform-eng/tile-generator#281]
Feature proposal:

It would be awesome to have a schema we could validate our `tile.yml` against before running the generator and getting into trouble that's not caught until installing the tile. Even if the schema wasn't 100% comprehensive and was overly strict, a `--strict` mode or `validate` sub-command would be awesome to catch things like bad types in forms, incompatible options and the like.

I'd much rather develop against something that was too strict but was guaranteed to produce things that would work than something that's too permissive and doesn't catch things until too late.

**Comment by keshto** [comment]
We have schema to cover most parts of tile.yml

**Comment by josephlewis42** [comment]
Hi @keshto is the schema public somewhere? I'd like to be able to validate my tile YAML as part of my CI process
