### ISSUE TITLE
Automate finding the latest version of ubuntu-xenial stemcell like we do for trusty

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#283]
See https://github.com/cf-platform-eng/tile-generator/blob/a145b20bcaedc554ea9fa457afc49439ea5f426e/tile_generator/config.py#L285

We should that for ubuntu-xenial stemcells too.

**Comment by mmambrose** [comment]
Is this being actively worked on? if not i'd be interested in taking a stab at it.

**Comment by mboldt** [comment]
Not being worked on afaik. Grab @keshto or me for any guidance.

Like I said in our slack conversation, imho we can do this for *only* xenial at this point, and make folks using trusty manually set the stemcell version (trusty is going out of support in a few months anyway).

**Comment by mmambrose** [comment]
We've implemented this in PR #293 - let me know if you have any questions!

**Comment by mboldt** [comment]
#293 merged. Thanks!
