### ISSUE TITLE
Optionally generate compiled releases when building tiles

### ISSUE THREAD

**Issue by spikymonkey** [cf-platform-eng/tile-generator#287]
Ideally we'd like our tiles to incorporate [compiled releases](https://bosh.io/docs/compiled-releases/) since they result in much faster tile installations.

If we had a bosh director and a set of credentials we could use for release compilation, would it be possible for `tile build` to make use of it and build compiled releases into the generated tile?

**Comment by keshto** [comment]
Please use the new dev `release_overrides` keyword in your tile to include compiled releases. See below example:
```
---
name: credhub-service-broker
icon_file: resources/icon.png
label: CredHub Service Broker
description: A service broker for storing credentials securely with CredHub

packages:
- name: credhub-broker
  type: app-broker
  label: CredHub Service Broker
  enable_global_access_to_plans: true
  pre_start_file: resources/pre_start.sh
  manifest:
    path: bin/linux_amd64/credhub-service-broker
    buildpack: binary_buildpack
    command: ./credhub-service-broker
    memory: 256M
 release_overides:
   cf-cli-release:
     name: cf-cli-release
     path: https://bosh.io/d/github.com/bosh-packages/cf-cli-COMPILED-release
