### ISSUE TITLE
`pcf settings` broken in 13.0.0

### ISSUE THREAD

**Issue by mheath** [cf-platform-eng/tile-generator#300]
When I run `pcf settings` with 13.0.0, it doesn't output anything. With pcf 12.0.8 (I haven't validate with other versions yet) it works just fine.

**Comment by mboldt** [comment]
Verified this happens in 12.0.9 as well (I.e, no output in 12.0.9).

**Comment by mboldt** [comment]
Bad whitespace in a prior commit; should be restored now. Thank you for reporting!
