### ISSUE TITLE
Use cf cli bosh release instead of packaging our own

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#306]
There's already a cf cli bosh release here: https://github.com/bosh-packages/cf-cli-release

We should use that instead of creating our own bosh package for it.

**Comment by mboldt** [comment]
Here is the code that could be replaced with including the cf cli bosh release: https://github.com/cf-platform-eng/tile-generator/blob/56b602334edb38639bc7e01b1e9e68e43f9e6828/tile_generator/package_flags.py#L99-L111

And a couple spots where it is used:
https://github.com/cf-platform-eng/tile-generator/blob/d2f8812ed972920dbc65a743879a0fb9be07a3e8/tile_generator/templates/jobs/deploy-all.sh.erb#L73
https://github.com/cf-platform-eng/tile-generator/blob/0f4f2010a7ba3fec52fca20f9edec48e3fadf5f0/tile_generator/templates/jobs/delete-all.sh.erb#L42

**Comment by keshto** [comment]
Done!
