### ISSUE TITLE
Release 14.0.0 tile binary won't run in ubuntu xenial or bionic

### ISSUE THREAD

**Issue by dyroberts** [cf-platform-eng/tile-generator#317]
Running the `tile` binary in ubuntu xenial or bionic returns the following error:

```[12] Error loading Python lib '/tmp/_MEI0gpyhp/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEI0gpyhp/libpython3.7m.so.1.0)```

`GLIBC_2.28` seems to be a cosmic specific package version. Cosmic is [end-of-life](https://wiki.ubuntu.com/Releases).

**Comment by keshto** [comment]
Fix is already in the pre-releases. Will cut a new stable release.
