### ISSUE TITLE
Clicking upgrade more than once in Ops Manager results in 500 error

### ISSUE THREAD

**Issue by bar-jakubovitz** [cf-platform-eng/tile-generator#33]
When trying to add/upgrade a new version of a tile, clicking the add/upgrade button on the package more then once some times result in a 500 server error.

this is due to trying to launch the add/upgrade job twice before the button is disabled.

**Comment by guidowb** [comment]
Will forward this issue to the Ops Manager team

**Comment by mreider** [comment]
Hi there. I am the product manager for Ops Manager. I have created a bug for this in our tracker. I also want to comment on the severity of the issue given our current concerns and close the issue based on my judgement of that severity. While we would like to live by the principle that 500 errors never appear under any circumstances, our team is hard pressed to deliver valuable infrastructure features and flexibility in our integration points with BOSH. After, and during, this work we will be rethinking our UX, and many of the interaction patterns we currently employ. This bug will disappear without being addressed directly as the current interaction for adding / upgrading tiles will disappear.

**Comment by guidowb** [comment]
Closing this tile-generator issue it will be tracked in Ops Manager per mreider above.
