### ISSUE TITLE
Services with space in the name result in a 500 error in apps manager marketplace

### ISSUE THREAD

**Issue by bar-jakubovitz** [cf-platform-eng/tile-generator#34]
If a service registers to CF marketplace and the service name contain space (" ") in it.
when that service is clicked on in the apps manager marketplace to view the plans a 500 error is returned.

**Comment by guidowb** [comment]
Bar, is this referring to the service name in the catalog returned by the service broker?

**Comment by guidowb** [comment]
Sabha confirmed yes.

So this is really a service-broker issue, and it would be nice if CC validated the service name(s) and returned a sensible error on create-service-broker. Will file that as an issue against CAPI.

Until it does, we _may_ be able to do the same validation in the code supplied by tile-generator, but only after the service-broker starts.
