### ISSUE TITLE
tile generation resulted in a corrupted tile

### ISSUE THREAD

**Issue by bar-jakubovitz** [cf-platform-eng/tile-generator#35]
happened in Nurego-tile ver 9-11 (uploaded to slot 3 pcf)
trying to untar the cf-cli/cf-linux-amd64.tgz resulted in "is not a valid tar file" error.
deleting all but the tile.yml and rebuild seemed to solve the problem, while just doing a rebuild seemed to result in more corrupt tiles

**Comment by mboldt** [comment]
We believe this happens when a download request gets a HTTP error and an HTML error page is downloaded instead of a tarball. We've fixed this by checking the status code of tile-generator's download requests.
