### ISSUE TITLE
Sometimes you really want the pipeline to use the specified stemcell

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#78]
@JaredGordon

**Comment by guidowb** [comment]
@JaredGordon added a --strict option to the configure command. If specified, it will not change the stemcell, but rather strictly use the one that is specified in the tile configuration file. If you want that behavior in a pipeline, add the --strict option to the configure command in your deploy script.

**Comment by JaredGordon** [comment]
Thanks Guido!
