### ISSUE TITLE
Specify install errands for 1.7 Ops Manager

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#93]
Right now, ops manager install hard codes `deploy-all` as the errand to run on 1.7. We have a tile that requires more than just `deploy-all` to run on install.

https://github.com/cf-platform-eng/tile-generator/blob/5e47212dbb6508b1be1ef597c19c509b7c358a0d/lib/opsmgr.py#L255

When you get a chance, we'd love the ability to override what errands to run.

**Comment by guidowb** [comment]
The current implementation is probably as good as it's going to get. For 1.7, in most cases, the errands must be specified because there is no reliable way to detect available errands through the API.
