### ISSUE TITLE
tile-generator fails with python3

### ISSUE THREAD

**Issue by prysmakou** [cf-platform-eng/tile-generator#96]
The generator expects Python2 but it is not mentioned in docs.

```
╰─➤  tile init
  File "/Users/alex/workspace/tile-generator/bin/tile", line 59
    print 'name:', config.get('name', '<unspecified>')
                ^
SyntaxError: invalid syntax
```

**Comment by guidowb** [comment]
You are correct. Thanks for filing the issue!

**Comment by mboldt** [comment]
I explored python3 support. In 92b0fba I got our unit tests passing in both python2 and python3. The only sticking point is our CLI library: http://click.pocoo.org/python3/. For now we will only support python2.

I've added an explicit note in the tile-generator documentation about the python2 requirement: http://cf-platform-eng.github.io/isv-portal/tile-generator/.
