### ISSUE TITLE
pcf configure does not work for job-specific properties

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#97]
1. If there are no top-level properties, pcf throws an exception (with the only indication being 'properties' on stderr)
2. The configure command will not find and/or set properties that are inside jobs

@jshah-pivotal

**Comment by mboldt** [comment]
Added for Ops Manager 1.8 in 08fa9ea. Won't add for 1.7 or earlier unless there's an urgent need.
