### ISSUE TITLE
Command-line option to dump version of tile-generator

### ISSUE THREAD

**Issue by gbertin** [cf-platform-eng/tile-generator#99]
Not high priority for us but adding versioning for these tools, in particular the "tile" command, would be helpful. We have multiple versions of the tile command in our build environment and it would be useful for traceability.  Something simple like:

./tile --version
0.0.123

**Comment by mboldt** [comment]
With the new delivery via `pip`, you can see the version of your tile-generator package with `pip show tile-generator | grep ^Version`.

**Comment by mboldt** [comment]
Upon more feedback and thought, we will make the version of tile-generator obvious from output logs, `tile --version`, or some way.

**Comment by keshto** [comment]
Done https://github.com/cf-platform-eng/tile-generator/commit/3b556450c6576be8c9edd59ed3fa8f5fd5422dae
